services:
      minimal_original.twig.extension.social:
          class: MinimalOriginal\SocialConnectBundle\Twig\Extension\SocialExtension
          arguments:
              - "%facebook.app.id%"
              - "%facebook.app.secret%"
              - "@router"
          tags:
              - { name: twig.extension }
      # Oauth
      minimal_original.authentication_provider.facebook:
          class: MinimalOriginal\SocialConnectBundle\Security\Authentication\Provider\FacebookAuthenticationProvider
          arguments: ['@minimal_original.user_provider.facebook']
          public: false

      minimal_original.user_provider.facebook:
          class: MinimalOriginal\SocialConnectBundle\Security\Core\User\FacebookUserProvider
          arguments: ['@fos_user.user_manager']
          public: false

      minimal_original.firewall_listener.facebook:
          class: MinimalOriginal\SocialConnectBundle\Security\Firewall\FacebookListener
          arguments: ['@security.token_storage', '@security.authentication.manager', '@router', '%facebook.app.id%', '%facebook.app.secret%']
          public: false
